Improved error reporting
DwcJava/engine pull request #217
Opened 2023-02-21 12:41 UTC by StephanWald

You can now add "debug" as command line argument in EM, or SET DEBUG=1 in your config.bbx file.

2023-02-22 10:05 UTC, hyyan requested changes

2023-02-22 10:05 UTC, hyyan commented on src/main/resources/bbj/dwcj.bbj
> +    if DEBUG=0 then
I think `DEBUG` is too generic. How about `DWJ_DEBUG`

2023-02-22 10:07 UTC, hyyan commented on src/main/resources/bbj/dwcj.bbj
> +        a=msgbox("An error has occured!",48,"Error")
Should we start logging the errors to a dwcj specific debug file too in here?

2023-02-23 10:40 UTC, StephanWald commented
merging what we have, more to be improved after refactor of structure

2023-02-23 10:40 UTC, merged