feat: BrowserStorage and setTerminateAction
DwcJava/engine pull request #382
Opened 2023-07-03 11:44 UTC by TimonGeisbauer

2023-07-04 08:05 UTC, hyyan requested changes

2023-07-04 08:05 UTC, hyyan commented on dwcj-engine/src/main/java/org/dwcj/CookieStorage.java
> +public class CookieStorage extends AbstractWebStorage {
The class does not provide method to add cookies using different samesite policies

2023-07-04 12:07 UTC, TimonGeisbauer commented on dwcj-engine/src/main/java/org/dwcj/AbstractWebStorage.java
> +      thinClient.setUserProperty(type.getValue(), key, null);
It set's the value of the key to null.
Attached a Sample.

```
package org.dwcj;

import org.dwcj.component.window.Frame;
import org.dwcj.component.window.Panel;
import org.dwcj.exceptions.DwcjException;

public class Demo extends App {

  @Override
  public void run() throws DwcjException {
    final Frame f = new Frame();
    final Panel p = new Panel();

    f.add(p);

    App.getCookieStorage().add("myCookie", "value");
    App.consoleLog(App.getCookieStorage().get("myCookie"));
    App.getCookieStorage().remove("myCookie");
    App.consoleLog(App.getCookieStorage().get("myCookie"));
  }

}
```

2023-12-11 12:32 UTC, MatthewHawkins approved these changes

2023-12-11 12:39 UTC, hyyan approved these changes

2023-12-11 12:39 UTC, merged