Fixed code smell issues on main branch, changed the IEventProxy use i…
DwcJava/engine pull request #53
Opened 2022-12-15 12:24 UTC by mhawkinsbasis

Fixed code smell issues on main branch, changed the IEventProxy use in BBjGridExWidgetSelectEventProxy, and renamed ButtonPushEvent to ButtonClickEvent (updated imports as well)

2022-12-15 13:11 UTC, hyyan commented
We should try reduce duplications before merging. duplications went from 4.0% to 20.1% with the PR

2022-12-16 11:00 UTC, mhawkinsbasis commented
Closes #46 #47 #52

2022-12-16 11:02 UTC, hyyan requested changes

2022-12-16 11:48 UTC, mhawkinsbasis commented on src/main/java/org/dwcj/controls/listbox/ListBox.java
> +import edu.emory.mathcs.backport.java.util.Collections;
This is being used in a few of the Listbox's methods that need to return an empty map i.e. getSelectedItems() which can return a Collections.emptyMap();

2022-12-16 12:02 UTC, hyyan commented on src/main/java/org/dwcj/controls/panels/Div.java
> +    public Div addClassName(String selector) {
We're going to address this later

2022-12-16 12:04 UTC, hyyan approved these changes

2022-12-16 12:05 UTC, hyyan commented on src/main/java/org/dwcj/controls/AbstractControl.java
> +        if (Boolean.TRUE.equals(Boolean.TRUE.equals(this.caughtUp))
@see https://github.com/DwcJava/engine/issues/59

2022-12-16 12:07 UTC, merged